modLoader = "javafml"
loaderVersion = "[43,)"
license="${mod_license}"

[[mods]]
modId = "quality_food"
displayTest="IGNORE_ALL_VERSION"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
${mod_description}
'''
itemIcon = "minecraft:cooked_chicken"

[[dependencies.quality_food]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quality_food]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"